let secretMessage = ['Learning', 'is', 'not', 'about', 'what', 'you', 'get', 'easily', 'the', 'first', 'time,', 'it', 'is', 'about', 'what', 'you', 'can', 'figure', 'out.', '-2015,', 'Chris', 'Pine,', 'Learn', 'JavaScript'];
  console.log(secretMessage.length);
 secretMessage.pop();
console.log(secretMessage.length);
secretMessage.push('t0', 'program');
console.log(secretMessage.length);
secretMessage[7] = 'right';
secretMessage.shift();
secretMessage.unshift('programming');
console.log(secretMessage.join());
secretMessage.splice(6, 10, 'know');
console.log(secretMessage.join(' '));